(in-package :shop-user)

(defproblem nfvmano-problem nfvmano-domain
	; Initial State
	(
		(HEALINGACTION migrate)
		(HEALINGTHRESHOLD policy-base-migrate-mem)
		(hasThreshold migrate policy-base-migrate-mem)
		(METRIC osm_pc_vim_mem_load)
		(hasMetric policy-base-migrate-mem osm_pc_vim_mem_load)
		(hasLowThresholdValue policy-base-migrate-mem 100)
		(hasMediumThresholdValue policy-base-migrate-mem 80)
		(hasHighThresholdValue policy-base-migrate-mem 70)
		(HEALINGTHRESHOLD policy-base-migrate-cpu)
		(hasThreshold migrate policy-base-migrate-cpu)
		(METRIC osm_pc_vim_cpu_load)
		(hasMetric policy-base-migrate-cpu osm_pc_vim_cpu_load)
		(hasLowThresholdValue policy-base-migrate-cpu 100)
		(hasMediumThresholdValue policy-base-migrate-cpu 80)
		(hasHighThresholdValue policy-base-migrate-cpu 70)
		(HEALINGTHRESHOLD policy-base-migrate-pnic-tx-dropped)
		(hasThreshold migrate policy-base-migrate-pnic-tx-dropped)
		(METRIC osm_pc_vim_phynic_tx_dropped)
		(hasMetric policy-base-migrate-pnic-tx-dropped osm_pc_vim_phynic_tx_dropped)
		(hasLowThresholdValue policy-base-migrate-pnic-tx-dropped 50)
		(hasMediumThresholdValue policy-base-migrate-pnic-tx-dropped 30)
		(hasHighThresholdValue policy-base-migrate-pnic-tx-dropped 10)
		(HEALINGTHRESHOLD policy-base-migrate-pnic-rx-dropped)
		(hasThreshold migrate policy-base-migrate-pnic-rx-dropped)
		(METRIC osm_pc_vim_phynic_rx_dropped)
		(hasMetric policy-base-migrate-pnic-rx-dropped osm_pc_vim_phynic_rx_dropped)
		(hasLowThresholdValue policy-base-migrate-pnic-rx-dropped 50)
		(hasMediumThresholdValue policy-base-migrate-pnic-rx-dropped 30)
		(hasHighThresholdValue policy-base-migrate-pnic-rx-dropped 10)
		(HEALINGACTION turnoff)
		(HEALINGACTION restart)
		(HEALINGACTION redeploy)
		(SCALINGACTION horizontal_scale)
		(SCALINGTHRESHOLD policy-base-scale-cpu)
		(hasThreshold horizontal_scale policy-base-scale-cpu)
		(METRIC osm_pc_vm_cpu_load)
		(hasMetric policy-base-scale-cpu osm_pc_vm_cpu_load)
		(hasLowScaleInThresholdValue policy-base-scale-cpu 30)
		(hasLowScaleOutThresholdValue policy-base-scale-cpu 90)
		(hasMediumScaleInThresholdValue policy-base-scale-cpu 20)
		(hasMediumScaleOutThresholdValue policy-base-scale-cpu 70)
		(hasHighScaleInThresholdValue policy-base-scale-cpu 10)
		(hasHighScaleOutThresholdValue policy-base-scale-cpu 50)
		(GOAL goal-base)
		(NS goal-base-ns-2599ab88-aaab-4d26-9513-e9d064b0549b)
		(hasNS goal-base goal-base-ns-2599ab88-aaab-4d26-9513-e9d064b0549b)
		(VNF goal-base-vnf-2)
		(hasVNF goal-base goal-base-vnf-2)
		(hasMemberVNFIndex goal-base-vnf-2 2)
		(VNF goal-base-vnf-1)
		(hasVNF goal-base goal-base-vnf-1)
		(hasMemberVNFIndex goal-base-vnf-1 1)
		(LEVEL low)
		(hasLevel goal-base low)
	)
	; Task List
	(:ordered
		(:task resilience_goal_achieved)
		(:task print-current-state)
	))

(find-plans 'nfvmano-problem :verbose :plans)
